---
- hosts: all
  tasks:
    - name: List project directory on the test system
      command: ls -al {{zuul.project.src_dir}}
    - name: install dependencies
      become: yes
      package:
        name:
          - python3-tox
        state: present
    - name: run pytest
      command:
        chdir: '{{zuul.project.src_dir}}'
        cmd: python -m tox
